application: calvins-cs373-wc
version: 1
runtime: python
api_version: 1

handlers:
- url: /test.*
  script: gaeunit.py

- url: /import
  script: helloworld.py

- url: /export
  script: goodbyeworld.py

- url: /upload
  script: helloworld.py

- url: /crises
  script: crisislist.py

- url: /crisis/.*
  script: crisis.py

- url: /people
  script: personlist.py

- url: /person/.*
  script: person.py

- url: /org/.*
  script: org.py

- url: /orgs
  script: orglist.py

- url: /scripts
  static_dir: scripts

- url: /style
  static_dir: style

- url: /images
  static_dir: images

- url: /
  upload: index.html
  static_files: index.html

- url: /index.html
  upload: index.html
  static_files: index.html
