application: calvins-cs373-wc
version: 1
runtime: python
api_version: 1

handlers:

- url: /import
  script: helloworld.py

- url: /export
  script: goodbyeworld.py

- url: /upload
  script: helloworld.py

- url: /crisis
  static_dir: crisis  

- url: /orgs
  static_dir: orgs  

- url: /people
  static_dir: people  

- url: /
  upload: index.html
  static_files: index.html
