application: calvins-cs373-wc
version: 1
runtime: python
api_version: 1

handlers:
- url: /test.*
  script: gaeunit.py

- url: /html
  static_dir: html
  
- url: /.*
  script: helloworld.py

- url: /test.*
script: gaeunit.py
