application: calvins-cs373-wc
version: 1
runtime: python
api_version: 1

handlers:

- url: /import
  script: helloworld.py

- url: /html
  static_dir: html
  
- url: /
  upload: html/index.html
  static_files: html/index.html
