application: calvins-cs373-wc
version: 1
runtime: python
api_version: 1

handlers:
- url: /test.*
  script: src/gaeunit.py

- url: /import
  script: src/helloworld.py

- url: /export
  script: src/goodbyeworld.py

- url: /upload
  script: src/helloworld.py

- url: /crises
  script: src/crisislist.py

- url: /crisis/.*
  script: src/crisis.py

- url: /people
  script: src/personlist.py

- url: /person/.*
  script: src/person.py

- url: /org/.*
  script: src/org.py

- url: /orgs
  script: src/orglist.py

- url: /scripts
  static_dir: scripts

- url: /style
  static_dir: style

- url: /images
  static_dir: images

- url: /.*
  upload: index.html
  static_files: index.html
